package networktool.gui.map;

import networktool.gui.components.GuiNetworkMap;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class MapNodeStyleTest {

    private GuiNetworkMap.Node node(String ip, String hn, String os, GuiNetworkMap.NodeType type) {
        return new GuiNetworkMap.Node(ip, hn, os, type);
    }

    @Test void iconForGateway() {
        assertEquals("G", MapNodeStyle.nodeIcon(node("1.1.1.1", "gw", null, GuiNetworkMap.NodeType.GATEWAY)));
    }

    @Test void iconForSelf() {
        assertEquals("*", MapNodeStyle.nodeIcon(node("1.1.1.1", "me", null, GuiNetworkMap.NodeType.SELF)));
    }

    @Test void iconForSwitch() {
        assertEquals("S", MapNodeStyle.nodeIcon(node("1.1.1.1", "sw", null, GuiNetworkMap.NodeType.SWITCH)));
    }

    @Test void iconForWindowsHost() {
        assertEquals("W", MapNodeStyle.nodeIcon(node("1.1.1.1", "pc", "Windows 11", GuiNetworkMap.NodeType.HOST)));
    }

    @Test void iconForLinuxHost() {
        assertEquals("L", MapNodeStyle.nodeIcon(node("1.1.1.1", "srv", "Linux", GuiNetworkMap.NodeType.HOST)));
    }

    @Test void iconForUnknownOsIsQuestionMark() {
        assertEquals("?", MapNodeStyle.nodeIcon(node("1.1.1.1", "h", null, GuiNetworkMap.NodeType.HOST)));
    }

    @Test void infraRoleOverridesTypeIcon() {
        // Switch-Typ mit DNS-Server-Rolle im os-Feld → D statt S
        assertEquals("D", MapNodeStyle.nodeIcon(
                node("1.1.1.1", "dns", "DNS-Server", GuiNetworkMap.NodeType.SWITCH)));
    }

    @Test void radiusIsLargerForInfrastructure() {
        int gwR = MapNodeStyle.nodeRadius(node("1.1.1.1", "gw", null, GuiNetworkMap.NodeType.GATEWAY));
        int hostR = MapNodeStyle.nodeRadius(node("1.1.1.2", "h", null, GuiNetworkMap.NodeType.HOST));
        assertTrue(gwR > hostR);
    }

    @Test void isInfraSwitchTrueForDnsRole() {
        GuiNetworkMap.Node n = node("1.1.1.1", "dns", "DNS-Server", GuiNetworkMap.NodeType.SWITCH);
        assertTrue(MapNodeStyle.isInfraSwitch(n));
    }

    @Test void isInfraSwitchFalseForPlainSwitch() {
        GuiNetworkMap.Node n = node("1.1.1.1", "sw", "Cisco Catalyst", GuiNetworkMap.NodeType.SWITCH);
        assertFalse(MapNodeStyle.isInfraSwitch(n));
    }

    @Test void isInfraSwitchFalseForHost() {
        GuiNetworkMap.Node n = node("1.1.1.1", "h", "DNS-Server", GuiNetworkMap.NodeType.HOST);
        assertFalse(MapNodeStyle.isInfraSwitch(n));
    }

    @Test void cleanHostnameReturnsNullWhenEqualsIp() {
        assertNull(MapNodeStyle.cleanHostname("10.0.0.5", "10.0.0.5"));
    }

    @Test void cleanHostnameReturnsNullForAutoGenerated() {
        assertNull(MapNodeStyle.cleanHostname("host-10", "10.0.0.5"));
    }

    @Test void cleanHostnameTruncatesLongNames() {
        String result = MapNodeStyle.cleanHostname("this-is-a-very-long-hostname-indeed", "10.0.0.5");
        assertNotNull(result);
        assertTrue(result.length() <= 18);
        assertTrue(result.endsWith("…"));
    }

    @Test void cleanHostnameStripsMacSuffix() {
        assertEquals("myhost", MapNodeStyle.cleanHostname("myhost [AA:BB:CC:DD:EE:FF]", "10.0.0.5"));
    }

    @Test void extractRoleLabelForKnownRoles() {
        assertEquals("DNS",  MapNodeStyle.extractRoleLabel("DNS-Server"));
        assertEquals("DHCP", MapNodeStyle.extractRoleLabel("DHCP-Server / Linux"));
        assertEquals("NTP",  MapNodeStyle.extractRoleLabel("NTP-Server"));
    }

    @Test void extractRoleLabelReturnsNullForPlainOs() {
        assertNull(MapNodeStyle.extractRoleLabel("Windows 11"));
        assertNull(MapNodeStyle.extractRoleLabel(null));
    }
}
